#DEV ENVIRONEMNT SETTING#


spring:  
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: latest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY:-1
    username: sa
    password: sa
    
app:
  message: This is the property file for the ${spring.application.name} specific to DEV Environment

api:
  name: /koop/api/v1/dev

koop:
  topic-name: checkout
  messages-per-request: 10